CREATE UNIQUE INDEX USR_INDEX ON USR(userId);
CREATE INDEX NAME_INDEX ON USR(name);
CREATE INDEX WORK_EXPR_INDEX ON WORK_EXPR(userId, company, role, startDate);
CREATE INDEX EDUCATIONAL_DETAILS_INDEX ON EDUCATIONAL_DETAILS(userId, major, degree);
CREATE INDEX MESSAGE_INDEX on MESSAGE(msgId);
CREATE INDEX CONNECTION_USR_INDEX on CONNECTION_USR(userId, connectionId);
