CREATE UNIQUE INDEX USR_INDEX ON USR(userid);
CREATE INDEX NAME_INDEX ON USR(name)l
CREATE INDEX WORK_EXPR_INDEX ON WORK_EXPR(userId, company, role, startDate);
CREATE INDEX EDUCATIONAL_DETAILS_INDEX ON EDUCATION_DETAILS(userId, major, degree);
CREATE INDEX MESSAGE_INDEX on MESSAGE(msgId);
CREATE INDEX CONNECTION_USR_INDEX on MESSAGE(userId, connectionId);
